### ISSUE TITLE
[Bug] Blocking falling out of from vehicle

### ISSUE THREAD

**Issue by Enerv** [altmp/altv#278]
I found that flag 32 is responsible for blocking the fall of the vehicle. Part of it works, it is harder to fall out of the vehicle but at very high speed it is possible. I was looking for other natives but I didn't find any.

## Expected Behavior
It should block the total falling out of the vehicle.

## Current Behavior
During a violent impact at high speed, the character falls out of the vehicle (should stay in it).

## Steps to Reproduce
```js
const player = alt.Player.local;
game.setPedCanRagdoll(player.scriptID, false); // Optional - disable ragdoll after fall out - it's works.
game.setPedConfigFlag(player.scriptID, 32, true); // Disable fall out from the vehicle.
```

**Comment by vanessa** [comment]
@Enerv have you tried calling this once the player enters the vehicle or on everyTick? (just making sure all scenarios were tried)

**Comment by Lhoerion** [comment]
I've tested it and it really doesn't fall through windscreen with flagId 32 at high speed of 200 m/s.
Also I think the issue is in your native usage understanding, as you assume that `BOOL value` switch is uniform for every flag.
`FLAG_CAN_FLY_THRU_WINDSCREEN`, value of true enables it, false disables it.

**Comment by Enerv** [comment]
Changing the flag from `TRUE` to `FALSE` helped and call every ped handle change.
