### ISSUE TITLE
Add attribute 'build' to servers in masterlist API

### ISSUE THREAD

**Issue by derRAV3N** [altmp/altv#35]
Hey,

It could be quite useful to have servers in the masterlist API have an attribute 'build', to show the current buildnumber that the server is running on.

**Comment by dayvoo** [comment]
Current problem:
There are servers in the masterlist (f.e. "Connect and test char creator if you want") where users can not connect because the server is running a build which is not compatible with the current client. If i press "Connect" nothing happens.

Possible solutions:
1) Completely remove servers with old (incompatible) build from masterlist
or
2) Only display the available (compatible) servers for the user in masterlist

**Comment by derRAV3N** [comment]
I'd rather show a red exclamation mark with an on-hover explanation in the server's entry. That way people/devs know the server is only but not compatible.

**Comment by vadzz-dev** [comment]
Done
